### ISSUE TITLE
Line endings causing issues under linux/osx when installed through yarn

### ISSUE THREAD

**Issue by dennis-c** [bartekbp/typescript-checkstyle#1]
First of all thank you for making this, it is exactly what I need for my CI. It works perfectly if packages have been installed through npm, however if yarn (v1) has been used it crashes with the following message.

Command:
```user@machine$  ./node_modules/.bin/typescript-checkstyle```

Error:
```env: node\r: No such file or directory```

I suspect this is because your file line endings are windows based (CRLF) instead of linux based (LF). Is there any chance you could change this?

**Comment by bartekbp** [comment]
Hi Dennis,

Thank you for your great words! I wondered if the package would be helpful for someone else and you just proved that it's indeed the case. It's extremely motivating:)

I checked the issue and it's caused by typescript default of using platform dependent line endings while emitting javascript files and the fact that I'm building the package on windows, so CRLF line endings got into the script. 

To fix it, I overrode the default in tsconfig.json in https://github.com/bartekbp/typescript-checkstyle/commit/d62c7fdbaf30d9369c0f0e142c7ba85372ab1f27, rebuilt artifacts, and published a new version of the tool to npm. Update to it (version 5) and the problem should be gone.

Thanks once again for reporting this issue!

**Comment by dennis-c** [comment]
Hi @bartekbp , sorry for the late reply, but it works like a charm 😄  See below for a little snipped of what it looks like in our Jenkins pipeline.
![Screenshot 2021-07-26 at 17 15 40](https://user-images.githubusercontent.com/1841343/127013973-8c2153a5-e26c-4e1c-8672-45b47df57fa4.png)
Thanks again!
